services:
  webapp:
    image: bike-sharing-webapp
    build: ./webapp
    restart: always
    env_file:
      - database.conf
      - security.conf
    ports:
      - 80:5000
    depends_on:
      - database

  database:
    image: postgres
    restart: always
    volumes: 
      - postgres_volume:/var/lib/postgresql/data
    env_file:
      - database.conf

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres_volume:
    
